### PR TITLE
Fixup call to /usr/bin/free

### PR DESCRIPTION
**Pull request by olifre**
Since debian stretch, "free" correctly complains:
free: Multiple unit options doesn't make sense.
So just give the unit option we actually want.

### CODE REVIEW

**Comment by olifre** [comment]
Actually, this still fails, since the format changed...
```
# /usr/bin/free -k
              total        used        free      shared  buff/cache   available
Mem:         961752      547604       59764        7864      354384      345944
Swap:        511996       27608      484388
```
Is there any reason not to use
`MemAvailable` from `/proc/meminfo` ?

**Comment by GermanBluefox** [comment]
Thanks for PR. I will test it and then will merge.

**Comment by olifre** [comment]
> Thanks for PR. I will test it and then will merge.

Thanks. I think the PR is still not correct. However, parsing `MemAvailable` from `/proc/meminfo´ instead appears to work fine, at least on Stretch. 
I don't have a Jessie system to confirm this does not break there...

**Comment by GermanBluefox** [comment]
Is it PR now correct?

**Comment by olifre** [comment]
This has been fixed for good by:
https://github.com/ioBroker/ioBroker.rpi2/commit/42bf1a3e552249bf2cb1d1d2bb70f13aecd1ee85
So let's close it ;-).

**Pull request closed without merging**
